# Notebook 06 – Executive Dashboard Data Preparation

## Objective

Prepare optimized datasets for Power BI dashboards using the engineered Feature Store.

### Outputs

- Executive Dashboard
- Financial Dashboard
- Inventory Dashboard
- Sales Dashboard
- Waste Dashboard
- Supplier Dashboard
- Category Dashboard
- Medicine Dashboard

All exported datasets will be stored in:

outputs/dashboard_data/

In [1]:
import pandas as pd
import numpy as np

from pathlib import Path
import os
import warnings

warnings.filterwarnings("ignore")

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)
pd.set_option("display.float_format", "{:,.2f}".format)

print("="*80)
print("ALL REQUIRED LIBRARIES LOADED SUCCESSFULLY")
print("="*80)

================================================================================
ALL REQUIRED LIBRARIES LOADED SUCCESSFULLY
================================================================================

In [2]:
dashboard_folder = Path("../../outputs/dashboard_data")

dashboard_folder.mkdir(

    parents=True,

    exist_ok=True

)

print("="*80)
print("DASHBOARD OUTPUT FOLDER READY")
print("="*80)
print(dashboard_folder.resolve())

================================================================================
DASHBOARD OUTPUT FOLDER READY
================================================================================
C:\Users\venka\OneDrive\Desktop\PharmaOps-AI\outputs\dashboard_data

In [3]:
feature_store = pd.read_csv(

    "../../outputs/processed_data/Feature_Store.csv"

)

print("="*80)
print("FEATURE STORE LOADED SUCCESSFULLY")
print("="*80)

print(f"Rows    : {feature_store.shape[0]:,}")
print(f"Columns : {feature_store.shape[1]:,}")

display(feature_store.head())

================================================================================
FEATURE STORE LOADED SUCCESSFULLY
================================================================================
Rows    : 4,954
Columns : 86

,Inventory_ID,Medicine_ID,Supplier_ID,Batch_Number,Manufacturing_Date,Expiry_Date,Quantity_In_Stock,Unit_Cost,Selling_Price,Reorder_Level,Storage_Temperature,Warehouse_Location,Stock_Status,Last_Restock_Date,Product_NDC,Generic_Name,Brand_Name,Manufacturer,Active_Ingredient,Strength,Dosage_Form,Route,Pharm_Class,Category_ID,Supplier_Name,Supplier_Type,Supplier_Category,Preferred_Supplier,City,State,Contact_Email,Contact_Number,Lead_Time_Days,Supplier_Rating,Active_Status,Contract_Start_Date,Contract_End_Date,GST_Number,Category_Name,Description,Total_Revenue,Total_Quantity_Sold,Average_Discount,Total_Transactions,Total_Waste_Value,Total_Quantity_Wasted,Inventory_Value,Potential_Sales_Value,Potential_Gross_Profit,Profit_per_Unit,Profit_Margin_Percentage,Markup_Percentage,Revenue_per_Transaction,Revenue_per_Unit_Sold,Inventory_ROI,Cost_to_Revenue_Ratio,Days_to_Expiry,Inventory_Age_Days,Days_Since_Last_Restock,Stock_Difference,Stock_Coverage_Ratio,Low_Stock_Flag,Overstock_Flag,Out_of_Stock_Flag,Expiry_Risk,Near_Expiry_Flag,Inventory_Health_Score,Business_Priority,Cumulative_Inventory_Value,Cumulative_Percentage,ABC_Class,Inventory_Criticality,Stock_Priority,Revenue_Percentile,Revenue_Category,Sales_Percentile,Movement_Type,High_Revenue_Flag,Sales_Performance_Score,Waste_Cost_Ratio,Waste_Percentage,Waste_Risk,Supplier_Performance_Index,Supplier_Risk,Executive_Risk_Score,Executive_Priority
0,INV002361,MED000911,SUP0048,BAT820020,2026-03-06,2027-03-31,993,596.32,798.36,87,Refrigerated (2â€“8Â°C),WH-A,In Stock,2026-05-07,76420-836,Gabapentin,Gabapentin,"Asclemed Usa, Inc.",GABAPENTIN,600 mg/1,TABLET,ORAL,Decreased Central Nervous System Disorganized ...,CAT005,Universal Pharma Traders,Wholesaler,Domestic,Yes,Hyderabad,Telangana,procurement@universaltraders.in,6562697526,4,4.00,Inactive,2025-05-31,2028-05-30,36SIAKF8196E1Z5,Neurology,Medicines for neurological disorders and the c...,0.00,0.00,0.00,0.00,0.00,0.00,"592,145.76","792,771.48","200,625.72",202.04,25.31,33.88,0.00,0.00,33.88,74.69,236,154,92,906,11.41,0,1,0,Low,0,90,Low,"592,145.76",0.08,A,High,Reduce Inventory,0.07,Low,0.07,Slow Moving,0,25.40,0.00,0.00,Low,76.00,Low,66.79,Medium
1,INV004233,MED056437,SUP0058,BAT986959,2026-03-05,2027-03-30,986,597.63,806.78,118,Frozen (-20Â°C),WH-A,In Stock,2026-04-23,98132-316,Titanium Dioxide,Bareminerals Barepro Performance Wear Liquid F...,Orveon Global Us Llc,TITANIUM DIOXIDE,33.2 mg/mL,LIQUID,TOPICAL,UNKNOWN,CAT015,RK Pharma Agencies,Wholesaler,Domestic,No,Visakhapatnam,Andhra Pradesh,procurement@rkagencies.in,8489250532,4,4.30,Active,2022-12-26,2025-12-25,37DOZNX8284Z1Z5,Others,Medicines that do not fit into the predefined ...,"1,593.69",6.00,5.00,3.00,"2,390.52",4.00,"589,263.18","795,485.08","206,221.90",209.15,25.92,35.00,531.23,265.62,35.00,74.08,235,155,106,868,8.36,0,1,0,Low,0,90,Low,"1,181,408.94",0.16,A,High,Reduce Inventory,0.43,Medium,0.66,Medium Moving,0,59.56,0.00,0.41,Low,82.00,Low,79.59,Medium
2,INV003424,MED000320,SUP0031,BAT669736,2026-01-22,2028-05-11,965,596.60,723.41,192,Frozen (-20Â°C),WH-E,In Stock,2026-03-21,0527-1927,Methadone Hydrochloride,"Methadone Hydrocloride Dye-Free, Sugar-Free, U...","Lannett Company, Inc.",METHADONE HYDROCHLORIDE,10 mg/mL,CONCENTRATE,ORAL,Full Opioid Agonists [MoA],CAT004,MedPlus Health Services,Distributor,Domestic,No,Hyderabad,Telangana,procurement@medplusmart.com,9155229266,6,4.30,Active,2025-10-01,2030-09-30,36USVXZ5956C1Z5,Pain Management,Pain relief and anti-inflammatory medicines,629.68,1.00,15.00,1.00,"4,772.80",8.00,"575,719.00","698,090.65","122,371.65",126.81,17.53,21.26,629.68,629.68,21.26,82.47,643,197,139,773,5.03,0,1,0,Low,0,90,Low,"1,757,127.94",0.24,A,High,Reduce Inventory,0.23,Low,0.19,Slow Moving,0,16.67,0.01,0.83,Low,80.00,Low,64.21,Medium
3,INV000760,MED096650,SUP0014,BAT840719,2023-11-01,2025-12-20,979,584.92,793.34,53,Frozen (-20Â°C),WH-A,In Stock,2024-03-12,82969-2192,"Berberis Vulg, Dulcamara, Equisetum Hyemle, Eu...",Bestmade Natural Products Bm192,Bestmade Natural Products,BERBERIS VULGARIS ROOT BARK,30 [hp_C]/30[hp_C],LIQUID,ORAL,UNKNOWN,CAT015,GSK Pharmaceuticals Ltd,Manufacturer,Domestic,No,Mumbai,Maharashtra,procurement@gsk.com,6707111048,13,4.20,Active,2023-08-08,2027-08-07,27SSURM1207B1Z5,Others,Medicines that do not fit into the predefined ...,"2,997.35",6.00,5.00,1.00,"10,528.56",18.00,"572,636.68","776,679.86","204,043.18",208.42,26.27,35.63,"2,997.35",499.56,35.63,73.73,-230,1010,878,926,18.47,0,1,0,Expired,1,65,Medium,"2,329,764.62",0.32,A,Critical,Reduce Inventory,0.64,High,0.66,Medium Moving,0,68.80,0.02,1.84,Low,71.00,Medium,72.20,Medium
4,INV003192,MED117869,SUP0010,BAT197330,2023-11-10,2025-08-31,998,572.69,774.24,32,Frozen (-20Â°C),WH-E,In Stock,2024-03-16,55910-986,Menthol,Dollar General Menthol Pain Relief Gel Rollon,"Dolgencorp, Llc",MENTHOL,4 g/mL,GEL,TOPICAL,UNKNOWN,CAT015,Glenmark Pharmaceuticals Ltd,Manufacturer,Domestic,No,Mumbai,Maharashtra,procurement@glenmarkpharma.com,7817363615,10,4.90,Active,2024-03-28,2029-03-27,27QLNDF3522C1Z5,Others,Medicines that do not fit into the predefined ...,332.00,1.00,0.00,1.00,0.00,0.00,"571,544.62","772,691.52","201,146.90",201.55,26.03,35.19,332.00,332.00,35.19,73.97,-341,1001,874,966,31.19,0,1,0,Expired,1,75,Low,"2,901,309.24",0.40,A,Critical,Reduce Inventory,0.18,Low,0.19,Slow Moving,0,35.54,0.00,0.00,Low,88.00,Medium,66.89,Medium

In [4]:
print("="*80)
print("FEATURE STORE VALIDATION")
print("="*80)

print(f"Rows              : {feature_store.shape[0]:,}")
print(f"Columns           : {feature_store.shape[1]:,}")
print(f"Duplicate Rows    : {feature_store.duplicated().sum():,}")
print(f"Missing Values    : {feature_store.isnull().sum().sum():,}")

print("\nColumn Names\n")

display(

    pd.DataFrame(

        feature_store.columns,

        columns=["Columns"]

    )

)

print("\n")

display(

    feature_store.head()

)

print("="*80)
print("VALIDATION COMPLETED SUCCESSFULLY")
print("="*80)

================================================================================
FEATURE STORE VALIDATION
================================================================================
Rows              : 4,954
Columns           : 86
Duplicate Rows    : 0
Missing Values    : 0

Column Names

                       Columns
0                 Inventory_ID
1                  Medicine_ID
2                  Supplier_ID
3                 Batch_Number
4           Manufacturing_Date
5                  Expiry_Date
6            Quantity_In_Stock
7                    Unit_Cost
8                Selling_Price
9                Reorder_Level
10         Storage_Temperature
11          Warehouse_Location
12                Stock_Status
13           Last_Restock_Date
14                 Product_NDC
15                Generic_Name
16                  Brand_Name
17                Manufacturer
18           Active_Ingredient
19                    Strength
20                 Dosage_Form
21                       Route
22                 Pharm_Class
23                 Category_ID
24               Supplier_Name
25               Supplier_Type
26           Supplier_Category
27          Preferred_Supplier
28                        City
29                       State
30               Contact_Email
31              Contact_Number
32              Lead_Time_Days
33             Supplier_Rating
34               Active_Status
35         Contract_Start_Date
36           Contract_End_Date
37                  GST_Number
38               Category_Name
39                 Description
40               Total_Revenue
41         Total_Quantity_Sold
42            Average_Discount
43          Total_Transactions
44           Total_Waste_Value
45       Total_Quantity_Wasted
46             Inventory_Value
47       Potential_Sales_Value
48      Potential_Gross_Profit
49             Profit_per_Unit
50    Profit_Margin_Percentage
51           Markup_Percentage
52     Revenue_per_Transaction
53       Revenue_per_Unit_Sold
54               Inventory_ROI
55       Cost_to_Revenue_Ratio
56              Days_to_Expiry
57          Inventory_Age_Days
58     Days_Since_Last_Restock
59            Stock_Difference
60        Stock_Coverage_Ratio
61              Low_Stock_Flag
62              Overstock_Flag
63           Out_of_Stock_Flag
64                 Expiry_Risk
65            Near_Expiry_Flag
66      Inventory_Health_Score
67           Business_Priority
68  Cumulative_Inventory_Value
69       Cumulative_Percentage
70                   ABC_Class
71       Inventory_Criticality
72              Stock_Priority
73          Revenue_Percentile
74            Revenue_Category
75            Sales_Percentile
76               Movement_Type
77           High_Revenue_Flag
78     Sales_Performance_Score
79            Waste_Cost_Ratio
80            Waste_Percentage
81                  Waste_Risk
82  Supplier_Performance_Index
83               Supplier_Risk
84        Executive_Risk_Score
85          Executive_Priority

,Inventory_ID,Medicine_ID,Supplier_ID,Batch_Number,Manufacturing_Date,Expiry_Date,Quantity_In_Stock,Unit_Cost,Selling_Price,Reorder_Level,Storage_Temperature,Warehouse_Location,Stock_Status,Last_Restock_Date,Product_NDC,Generic_Name,Brand_Name,Manufacturer,Active_Ingredient,Strength,Dosage_Form,Route,Pharm_Class,Category_ID,Supplier_Name,Supplier_Type,Supplier_Category,Preferred_Supplier,City,State,Contact_Email,Contact_Number,Lead_Time_Days,Supplier_Rating,Active_Status,Contract_Start_Date,Contract_End_Date,GST_Number,Category_Name,Description,Total_Revenue,Total_Quantity_Sold,Average_Discount,Total_Transactions,Total_Waste_Value,Total_Quantity_Wasted,Inventory_Value,Potential_Sales_Value,Potential_Gross_Profit,Profit_per_Unit,Profit_Margin_Percentage,Markup_Percentage,Revenue_per_Transaction,Revenue_per_Unit_Sold,Inventory_ROI,Cost_to_Revenue_Ratio,Days_to_Expiry,Inventory_Age_Days,Days_Since_Last_Restock,Stock_Difference,Stock_Coverage_Ratio,Low_Stock_Flag,Overstock_Flag,Out_of_Stock_Flag,Expiry_Risk,Near_Expiry_Flag,Inventory_Health_Score,Business_Priority,Cumulative_Inventory_Value,Cumulative_Percentage,ABC_Class,Inventory_Criticality,Stock_Priority,Revenue_Percentile,Revenue_Category,Sales_Percentile,Movement_Type,High_Revenue_Flag,Sales_Performance_Score,Waste_Cost_Ratio,Waste_Percentage,Waste_Risk,Supplier_Performance_Index,Supplier_Risk,Executive_Risk_Score,Executive_Priority
0,INV002361,MED000911,SUP0048,BAT820020,2026-03-06,2027-03-31,993,596.32,798.36,87,Refrigerated (2â€“8Â°C),WH-A,In Stock,2026-05-07,76420-836,Gabapentin,Gabapentin,"Asclemed Usa, Inc.",GABAPENTIN,600 mg/1,TABLET,ORAL,Decreased Central Nervous System Disorganized ...,CAT005,Universal Pharma Traders,Wholesaler,Domestic,Yes,Hyderabad,Telangana,procurement@universaltraders.in,6562697526,4,4.00,Inactive,2025-05-31,2028-05-30,36SIAKF8196E1Z5,Neurology,Medicines for neurological disorders and the c...,0.00,0.00,0.00,0.00,0.00,0.00,"592,145.76","792,771.48","200,625.72",202.04,25.31,33.88,0.00,0.00,33.88,74.69,236,154,92,906,11.41,0,1,0,Low,0,90,Low,"592,145.76",0.08,A,High,Reduce Inventory,0.07,Low,0.07,Slow Moving,0,25.40,0.00,0.00,Low,76.00,Low,66.79,Medium
1,INV004233,MED056437,SUP0058,BAT986959,2026-03-05,2027-03-30,986,597.63,806.78,118,Frozen (-20Â°C),WH-A,In Stock,2026-04-23,98132-316,Titanium Dioxide,Bareminerals Barepro Performance Wear Liquid F...,Orveon Global Us Llc,TITANIUM DIOXIDE,33.2 mg/mL,LIQUID,TOPICAL,UNKNOWN,CAT015,RK Pharma Agencies,Wholesaler,Domestic,No,Visakhapatnam,Andhra Pradesh,procurement@rkagencies.in,8489250532,4,4.30,Active,2022-12-26,2025-12-25,37DOZNX8284Z1Z5,Others,Medicines that do not fit into the predefined ...,"1,593.69",6.00,5.00,3.00,"2,390.52",4.00,"589,263.18","795,485.08","206,221.90",209.15,25.92,35.00,531.23,265.62,35.00,74.08,235,155,106,868,8.36,0,1,0,Low,0,90,Low,"1,181,408.94",0.16,A,High,Reduce Inventory,0.43,Medium,0.66,Medium Moving,0,59.56,0.00,0.41,Low,82.00,Low,79.59,Medium
2,INV003424,MED000320,SUP0031,BAT669736,2026-01-22,2028-05-11,965,596.60,723.41,192,Frozen (-20Â°C),WH-E,In Stock,2026-03-21,0527-1927,Methadone Hydrochloride,"Methadone Hydrocloride Dye-Free, Sugar-Free, U...","Lannett Company, Inc.",METHADONE HYDROCHLORIDE,10 mg/mL,CONCENTRATE,ORAL,Full Opioid Agonists [MoA],CAT004,MedPlus Health Services,Distributor,Domestic,No,Hyderabad,Telangana,procurement@medplusmart.com,9155229266,6,4.30,Active,2025-10-01,2030-09-30,36USVXZ5956C1Z5,Pain Management,Pain relief and anti-inflammatory medicines,629.68,1.00,15.00,1.00,"4,772.80",8.00,"575,719.00","698,090.65","122,371.65",126.81,17.53,21.26,629.68,629.68,21.26,82.47,643,197,139,773,5.03,0,1,0,Low,0,90,Low,"1,757,127.94",0.24,A,High,Reduce Inventory,0.23,Low,0.19,Slow Moving,0,16.67,0.01,0.83,Low,80.00,Low,64.21,Medium
3,INV000760,MED096650,SUP0014,BAT840719,2023-11-01,2025-12-20,979,584.92,793.34,53,Frozen (-20Â°C),WH-A,In Stock,2024-03-12,82969-2192,"Berberis Vulg, Dulcamara, Equisetum Hyemle, Eu...",Bestmade Natural Products Bm192,Bestmade Natural Products,BERBERIS VULGARIS ROOT BARK,30 [hp_C]/30[hp_C],LIQUID,ORAL,UNKNOWN,CAT015,GSK Pharmaceuticals Ltd,Manufacturer,Domestic,No,Mumbai,Maharashtra,procurement@gsk.com,6707111048,13,4.20,Active,2023-08-08,2027-08-07,27SSURM1207B1Z5,Others,Medicines that do not fit into the predefined ...,"2,997.35",6.00,5.00,1.00,"10,528.56",18.00,"572,636.68","776,679.86","204,043.18",208.42,26.27,35.63,"2,997.35",499.56,35.63,73.73,-230,1010,878,926,18.47,0,1,0,Expired,1,65,Medium,"2,329,764.62",0.32,A,Critical,Reduce Inventory,0.64,High,0.66,Medium Moving,0,68.80,0.02,1.84,Low,71.00,Medium,72.20,Medium
4,INV003192,MED117869,SUP0010,BAT197330,2023-11-10,2025-08-31,998,572.69,774.24,32,Frozen (-20Â°C),WH-E,In Stock,2024-03-16,55910-986,Menthol,Dollar General Menthol Pain Relief Gel Rollon,"Dolgencorp, Llc",MENTHOL,4 g/mL,GEL,TOPICAL,UNKNOWN,CAT015,Glenmark Pharmaceuticals Ltd,Manufacturer,Domestic,No,Mumbai,Maharashtra,procurement@glenmarkpharma.com,7817363615,10,4.90,Active,2024-03-28,2029-03-27,27QLNDF3522C1Z5,Others,Medicines that do not fit into the predefined ...,332.00,1.00,0.00,1.00,0.00,0.00,"571,544.62","772,691.52","201,146.90",201.55,26.03,35.19,332.00,332.00,35.19,73.97,-341,1001,874,966,31.19,0,1,0,Expired,1,75,Low,"2,901,309.24",0.40,A,Critical,Reduce Inventory,0.18,Low,0.19,Slow Moving,0,35.54,0.00,0.00,Low,88.00,Medium,66.89,Medium

================================================================================
VALIDATION COMPLETED SUCCESSFULLY
================================================================================

# SECTION A — Medicine Dimension (Dim_Medicine)

## Objective

Create the Medicine Dimension table containing descriptive information for every medicine.

This table serves as the master reference for medicine-related attributes and will be linked to the Fact_Medicine_Performance table using **Medicine_ID**.

### Primary Key

- Medicine_ID

### Business Purpose

- Medicine Details
- Product Details
- Drug Classification
- Category Mapping

In [5]:
print(feature_store.columns.tolist())

['Inventory_ID', 'Medicine_ID', 'Supplier_ID', 'Batch_Number', 'Manufacturing_Date', 'Expiry_Date', 'Quantity_In_Stock', 'Unit_Cost', 'Selling_Price', 'Reorder_Level', 'Storage_Temperature', 'Warehouse_Location', 'Stock_Status', 'Last_Restock_Date', 'Product_NDC', 'Generic_Name', 'Brand_Name', 'Manufacturer', 'Active_Ingredient', 'Strength', 'Dosage_Form', 'Route', 'Pharm_Class', 'Category_ID', 'Supplier_Name', 'Supplier_Type', 'Supplier_Category', 'Preferred_Supplier', 'City', 'State', 'Contact_Email', 'Contact_Number', 'Lead_Time_Days', 'Supplier_Rating', 'Active_Status', 'Contract_Start_Date', 'Contract_End_Date', 'GST_Number', 'Category_Name', 'Description', 'Total_Revenue', 'Total_Quantity_Sold', 'Average_Discount', 'Total_Transactions', 'Total_Waste_Value', 'Total_Quantity_Wasted', 'Inventory_Value', 'Potential_Sales_Value', 'Potential_Gross_Profit', 'Profit_per_Unit', 'Profit_Margin_Percentage', 'Markup_Percentage', 'Revenue_per_Transaction', 'Revenue_per_Unit_Sold', 'Inventory_ROI', 'Cost_to_Revenue_Ratio', 'Days_to_Expiry', 'Inventory_Age_Days', 'Days_Since_Last_Restock', 'Stock_Difference', 'Stock_Coverage_Ratio', 'Low_Stock_Flag', 'Overstock_Flag', 'Out_of_Stock_Flag', 'Expiry_Risk', 'Near_Expiry_Flag', 'Inventory_Health_Score', 'Business_Priority', 'Cumulative_Inventory_Value', 'Cumulative_Percentage', 'ABC_Class', 'Inventory_Criticality', 'Stock_Priority', 'Revenue_Percentile', 'Revenue_Category', 'Sales_Percentile', 'Movement_Type', 'High_Revenue_Flag', 'Sales_Performance_Score', 'Waste_Cost_Ratio', 'Waste_Percentage', 'Waste_Risk', 'Supplier_Performance_Index', 'Supplier_Risk', 'Executive_Risk_Score', 'Executive_Priority']

In [6]:
print("="*80)
print("CREATING MEDICINE DIMENSION")
print("="*80)

medicine_columns = [

    "Medicine_ID",

    "Product_NDC",

    "Generic_Name",

    "Brand_Name",

    "Manufacturer",

    "Active_Ingredient",

    "Strength",

    "Dosage_Form",

    "Route",

    "Pharm_Class",

    "Category_ID",

    "Category_Name"

]

dim_medicine = (

    feature_store[medicine_columns]

    .drop_duplicates(subset="Medicine_ID")

    .sort_values("Medicine_ID")

    .reset_index(drop=True)

)

print(f"Rows              : {dim_medicine.shape[0]:,}")

print(f"Columns           : {dim_medicine.shape[1]}")

print(f"Duplicate Records : {dim_medicine.duplicated().sum()}")

print(f"Missing Values    : {dim_medicine.isna().sum().sum()}")

print("="*80)

display(dim_medicine.head())

================================================================================
CREATING MEDICINE DIMENSION
================================================================================
Rows              : 4,824
Columns           : 12
Duplicate Records : 0
Missing Values    : 0
================================================================================

,Medicine_ID,Product_NDC,Generic_Name,Brand_Name,Manufacturer,Active_Ingredient,Strength,Dosage_Form,Route,Pharm_Class,Category_ID,Category_Name
0,MED000020,72162-1824,Temazepam,Temazepam,Bryant Ranch Prepack,TEMAZEPAM,15 mg/1,CAPSULE,ORAL,Benzodiazepine [EPC],CAT005,Neurology
1,MED000028,0480-2607,Sitagliptin,Sitagliptin,"Teva Pharmaceuticals, Inc.",SITAGLIPTIN PHOSPHATE,25 mg/1,"TABLET, FILM COATED",ORAL,Dipeptidyl Peptidase 4 Inhibitor [EPC],CAT002,Cardiovascular
2,MED000064,72162-2462,Losartan Potassium And Hydrochlorothiazide,Losartan Potassium And Hydrochlorothiazide,Bryant Ranch Prepack,HYDROCHLOROTHIAZIDE,12.5 mg/1,"TABLET, FILM COATED",ORAL,Angiotensin 2 Receptor Antagonists [MoA],CAT003,Diabetes
3,MED000077,72162-2608,Clobazam,Clobazam,Bryant Ranch Prepack,CLOBAZAM,2.5 mg/mL,SUSPENSION,ORAL,Benzodiazepine [EPC],CAT005,Neurology
4,MED000128,72189-635,Metformin Hcl,Metformin Hcl,Direct_Rx,METFORMIN HYDROCHLORIDE,1000 mg/1,TABLET,ORAL,Biguanide [EPC],CAT002,Cardiovascular

In [7]:
print("="*80)
print("MEDICINE DIMENSION VALIDATION")
print("="*80)

duplicate_keys = dim_medicine["Medicine_ID"].duplicated().sum()

print(f"Duplicate Medicine_ID : {duplicate_keys}")

print(f"Unique Medicines      : {dim_medicine['Medicine_ID'].nunique():,}")

print(f"Total Records         : {len(dim_medicine):,}")

if duplicate_keys == 0:

    print("\nSTATUS : PASSED")

else:

    print("\nSTATUS : FAILED")

================================================================================
MEDICINE DIMENSION VALIDATION
================================================================================
Duplicate Medicine_ID : 0
Unique Medicines      : 4,824
Total Records         : 4,824

STATUS : PASSED

In [8]:
print("="*80)
print("MEDICINE DIMENSION PROFILE")
print("="*80)

dim_medicine.info()

print("\n")

display(

    dim_medicine.describe(include="all").T

)

================================================================================
MEDICINE DIMENSION PROFILE
================================================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4824 entries, 0 to 4823
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Medicine_ID        4824 non-null   object
 1   Product_NDC        4824 non-null   object
 2   Generic_Name       4824 non-null   object
 3   Brand_Name         4824 non-null   object
 4   Manufacturer       4824 non-null   object
 5   Active_Ingredient  4824 non-null   object
 6   Strength           4824 non-null   object
 7   Dosage_Form        4824 non-null   object
 8   Route              4824 non-null   object
 9   Pharm_Class        4824 non-null   object
 10  Category_ID        4824 non-null   object
 11  Category_Name      4824 non-null   object
dtypes: object(12)
memory usage: 452.4+ KB

                  count unique                           top  freq
Medicine_ID        4824   4824                     MED137011     1
Product_NDC        4824   4824                     76282-348     1
Generic_Name       4824   2088                    Zinc Oxide    95
Brand_Name         4824   3193          Levothyroxine Sodium    28
Manufacturer       4824   1500  Hahnemann Laboratories, Inc.   195
Active_Ingredient  4824   1246                 ACETAMINOPHEN   173
Strength           4824   1066                       10 mg/1   143
Dosage_Form        4824    106                        TABLET   779
Route              4824     33                          ORAL  2886
Pharm_Class        4824    319                       UNKNOWN  1745
Category_ID        4824     14                        CAT015  1745
Category_Name      4824     14                        Others  1745

In [9]:
dim_medicine.to_csv(

    dashboard_folder /

    "Dim_Medicine.csv",

    index=False

)

print("="*80)
print("Dim_Medicine EXPORTED SUCCESSFULLY")
print("="*80)

print(dashboard_folder / "Dim_Medicine.csv")

================================================================================
Dim_Medicine EXPORTED SUCCESSFULLY
================================================================================
..\..\outputs\dashboard_data\Dim_Medicine.csv

In [10]:
import os

file_path = dashboard_folder / "Dim_Medicine.csv"

print("="*80)
print("EXPORT VALIDATION")
print("="*80)

if os.path.exists(file_path):

    print("STATUS : SUCCESS")

    print(f"File Name : {file_path.name}")

    print(f"File Size : {round(os.path.getsize(file_path)/1024,2)} KB")

else:

    print("STATUS : FAILED")

================================================================================
EXPORT VALIDATION
================================================================================
STATUS : SUCCESS
File Name : Dim_Medicine.csv
File Size : 858.58 KB

# SECTION B — Category Dimension (Dim_Category)

## Objective

Create the Category Dimension table containing descriptive information for every medicine category.

This table will provide category-level attributes for reporting and will be linked to the Fact_Medicine_Performance table using **Category_ID**.

### Primary Key

- Category_ID

### Business Purpose

- Category Classification
- Product Segmentation
- Business Reporting

In [11]:
print("="*80)
print("CREATING CATEGORY DIMENSION")
print("="*80)

category_columns = [

    "Category_ID",

    "Category_Name",

    "Description"

]

dim_category = (

    feature_store[category_columns]

    .drop_duplicates(subset="Category_ID")

    .sort_values("Category_ID")

    .reset_index(drop=True)

)

print(f"Rows              : {dim_category.shape[0]:,}")
print(f"Columns           : {dim_category.shape[1]}")
print(f"Duplicate Records : {dim_category.duplicated().sum()}")
print(f"Missing Values    : {dim_category.isnull().sum().sum()}")

print("="*80)

display(dim_category)

================================================================================
CREATING CATEGORY DIMENSION
================================================================================
Rows              : 14
Columns           : 3
Duplicate Records : 0
Missing Values    : 0
================================================================================

,Category_ID,Category_Name,Description
0,CAT001,Antibiotics,Medicines used to treat bacterial infections
1,CAT002,Cardiovascular,Medicines for heart and blood vessel disorders
2,CAT003,Diabetes,Medicines used for diabetes management
3,CAT004,Pain Management,Pain relief and anti-inflammatory medicines
4,CAT005,Neurology,Medicines for neurological disorders and the c...
5,CAT006,Respiratory,"Medicines for asthma, COPD, and other respirat..."
6,CAT007,Gastrointestinal,Medicines for digestive system disorders
7,CAT008,Dermatology,Medicines used for skin conditions
8,CAT009,Oncology,Medicines used in cancer treatment
9,CAT010,Allergy,Medicines used for allergies and immune responses
10,CAT012,Ophthalmology,Medicines used for eye diseases and vision care
11,CAT013,Vaccines & Biologics,"Vaccines, plasma products and biological medic..."
12,CAT014,Vitamins & Supplements,"Vitamins, minerals, nutritional supplements an..."
13,CAT015,Others,Medicines that do not fit into the predefined ...

In [12]:
print("="*80)
print("CATEGORY DIMENSION VALIDATION")
print("="*80)

duplicate_keys = dim_category["Category_ID"].duplicated().sum()

print(f"Duplicate Category_ID : {duplicate_keys}")
print(f"Unique Categories     : {dim_category['Category_ID'].nunique()}")
print(f"Total Records         : {len(dim_category)}")

if duplicate_keys == 0:
    print("\nSTATUS : PASSED")
else:
    print("\nSTATUS : FAILED")

================================================================================
CATEGORY DIMENSION VALIDATION
================================================================================
Duplicate Category_ID : 0
Unique Categories     : 14
Total Records         : 14

STATUS : PASSED

In [13]:
print("="*80)
print("CATEGORY DIMENSION PROFILE")
print("="*80)

dim_category.info()

print()

display(

    dim_category.describe(include="all").T

)

================================================================================
CATEGORY DIMENSION PROFILE
================================================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Category_ID    14 non-null     object
 1   Category_Name  14 non-null     object
 2   Description    14 non-null     object
dtypes: object(3)
memory usage: 464.0+ bytes

              count unique                                           top freq
Category_ID      14     14                                        CAT001    1
Category_Name    14     14                                   Antibiotics    1
Description      14     14  Medicines used to treat bacterial infections    1

In [14]:
dim_category.to_csv(

    dashboard_folder /

    "Dim_Category.csv",

    index=False

)

print("="*80)
print("Dim_Category EXPORTED SUCCESSFULLY")
print("="*80)

print(dashboard_folder / "Dim_Category.csv")

================================================================================
Dim_Category EXPORTED SUCCESSFULLY
================================================================================
..\..\outputs\dashboard_data\Dim_Category.csv

In [15]:
import os

file_path = dashboard_folder / "Dim_Category.csv"

print("="*80)
print("EXPORT VALIDATION")
print("="*80)

if os.path.exists(file_path):

    print("STATUS : SUCCESS")

    print(f"File Name : {file_path.name}")

    print(f"File Size : {round(os.path.getsize(file_path)/1024,2)} KB")

else:

    print("STATUS : FAILED")

================================================================================
EXPORT VALIDATION
================================================================================
STATUS : SUCCESS
File Name : Dim_Category.csv
File Size : 1.01 KB

# SECTION C — Supplier Dimension (Dim_Supplier)

## Objective

Create the Supplier Dimension table containing supplier master information.

This table supports procurement analysis and will be linked to the Fact_Medicine_Performance table using **Supplier_ID**.

### Primary Key

- Supplier_ID

### Business Purpose

- Supplier Performance
- Procurement Analytics
- Lead Time Analysis
- Vendor Management

In [16]:
print("="*80)
print("CREATING SUPPLIER DIMENSION")
print("="*80)

supplier_columns = [

    "Supplier_ID",

    "Supplier_Name",

    "Supplier_Type",

    "Supplier_Category",

    "Preferred_Supplier",

    "City",

    "State",

    "Lead_Time_Days",

    "Supplier_Rating",

    "Active_Status"

]

dim_supplier = (

    feature_store[supplier_columns]

    .drop_duplicates(subset="Supplier_ID")

    .sort_values("Supplier_ID")

    .reset_index(drop=True)

)

print(f"Rows              : {dim_supplier.shape[0]:,}")
print(f"Columns           : {dim_supplier.shape[1]}")
print(f"Duplicate Records : {dim_supplier.duplicated().sum()}")
print(f"Missing Values    : {dim_supplier.isnull().sum().sum()}")

print("="*80)

display(dim_supplier.head())

================================================================================
CREATING SUPPLIER DIMENSION
================================================================================
Rows              : 75
Columns           : 10
Duplicate Records : 0
Missing Values    : 0
================================================================================

,Supplier_ID,Supplier_Name,Supplier_Type,Supplier_Category,Preferred_Supplier,City,State,Lead_Time_Days,Supplier_Rating,Active_Status
0,SUP0001,Sun Pharmaceutical Industries Ltd,Manufacturer,Domestic,Yes,Mumbai,Maharashtra,8,4.20,Active
1,SUP0002,Dr. Reddy's Laboratories Ltd,Manufacturer,Domestic,No,Hyderabad,Telangana,10,4.60,Active
2,SUP0003,Cipla Ltd,Manufacturer,International,No,Mumbai,Maharashtra,14,4.60,Active
3,SUP0004,Lupin Ltd,Manufacturer,Domestic,No,Mumbai,Maharashtra,14,4.70,Active
4,SUP0005,Aurobindo Pharma Ltd,Manufacturer,Domestic,Yes,Hyderabad,Telangana,17,4.50,Active

In [17]:
print("="*80)
print("SUPPLIER DIMENSION VALIDATION")
print("="*80)

duplicate_keys = dim_supplier["Supplier_ID"].duplicated().sum()

print(f"Duplicate Supplier_ID : {duplicate_keys}")
print(f"Unique Suppliers      : {dim_supplier['Supplier_ID'].nunique()}")
print(f"Total Records         : {len(dim_supplier)}")

if duplicate_keys == 0:
    print("\nSTATUS : PASSED")
else:
    print("\nSTATUS : FAILED")

================================================================================
SUPPLIER DIMENSION VALIDATION
================================================================================
Duplicate Supplier_ID : 0
Unique Suppliers      : 75
Total Records         : 75

STATUS : PASSED

In [18]:
print("="*80)
print("SUPPLIER DIMENSION PROFILE")
print("="*80)

dim_supplier.info()

print()

display(

    dim_supplier.describe(include="all").T

)

================================================================================
SUPPLIER DIMENSION PROFILE
================================================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 75 entries, 0 to 74
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Supplier_ID         75 non-null     object
 1   Supplier_Name       75 non-null     object
 2   Supplier_Type       75 non-null     object
 3   Supplier_Category   75 non-null     object
 4   Preferred_Supplier  75 non-null     object
 5   City                75 non-null     object
 6   State               75 non-null     object
 7   Lead_Time_Days      75 non-null     int64
 8   Supplier_Rating     75 non-null     float64
 9   Active_Status       75 non-null     object
dtypes: float64(1), int64(1), object(8)
memory usage: 6.0+ KB

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Supplier_ID,75,75,SUP0001,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Supplier_Name,75,75,Sun Pharmaceutical Industries Ltd,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Supplier_Type,75,3,Manufacturer,30,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Supplier_Category,75,2,Domestic,68,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Preferred_Supplier,75,2,No,55,NaN,NaN,NaN,NaN,NaN,NaN,NaN
City,75,18,Mumbai,19,NaN,NaN,NaN,NaN,NaN,NaN,NaN
State,75,11,Maharashtra,25,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Lead_Time_Days,75.00,NaN,NaN,NaN,8.45,4.75,2.00,5.00,7.00,10.50,20.00
Supplier_Rating,75.00,NaN,NaN,NaN,4.35,0.37,3.50,4.15,4.40,4.60,5.00
Active_Status,75,2,Active,66,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
dim_supplier.to_csv(

    dashboard_folder /

    "Dim_Supplier.csv",

    index=False

)

print("="*80)
print("Dim_Supplier EXPORTED SUCCESSFULLY")
print("="*80)

print(dashboard_folder / "Dim_Supplier.csv")

================================================================================
Dim_Supplier EXPORTED SUCCESSFULLY
================================================================================
..\..\outputs\dashboard_data\Dim_Supplier.csv

In [20]:
import os

file_path = dashboard_folder / "Dim_Supplier.csv"

print("="*80)
print("EXPORT VALIDATION")
print("="*80)

if os.path.exists(file_path):

    print("STATUS : SUCCESS")

    print(f"File Name : {file_path.name}")

    print(f"File Size : {round(os.path.getsize(file_path)/1024,2)} KB")

else:

    print("STATUS : FAILED")

================================================================================
EXPORT VALIDATION
================================================================================
STATUS : SUCCESS
File Name : Dim_Supplier.csv
File Size : 6.69 KB

# SECTION D — Date Dimension (Dim_Date)

## Objective

Create a centralized Date Dimension table for Power BI.

This table consolidates all unique dates from:
- Manufacturing Date
- Expiry Date
- Last Restock Date

The Date Dimension enables efficient time-based reporting, trend analysis, and filtering across the Power BI dashboards.

### Primary Key

- Date

### Business Purpose

- Yearly Analysis
- Monthly Analysis
- Quarterly Analysis
- Weekly Analysis
- Time Intelligence

In [21]:
print("="*80)
print("CREATING DATE DIMENSION")
print("="*80)

date_columns = [

    "Manufacturing_Date",

    "Expiry_Date",

    "Last_Restock_Date"

]

all_dates = pd.concat(

    [

        pd.to_datetime(feature_store[col])

        for col in date_columns

    ]

).dropna().drop_duplicates().sort_values()

dim_date = pd.DataFrame({

    "Date": all_dates

})

dim_date["Year"] = dim_date["Date"].dt.year
dim_date["Quarter"] = "Q" + dim_date["Date"].dt.quarter.astype(str)
dim_date["Month"] = dim_date["Date"].dt.month
dim_date["Month_Name"] = dim_date["Date"].dt.month_name()
dim_date["Week"] = dim_date["Date"].dt.isocalendar().week.astype(int)
dim_date["Day"] = dim_date["Date"].dt.day
dim_date["Day_Name"] = dim_date["Date"].dt.day_name()
dim_date["Weekday"] = dim_date["Date"].dt.weekday + 1

print(f"Rows              : {len(dim_date):,}")
print(f"Columns           : {dim_date.shape[1]}")
print(f"Missing Values    : {dim_date.isnull().sum().sum()}")

print("="*80)

display(dim_date.head())

================================================================================
CREATING DATE DIMENSION
================================================================================
Rows              : 2,030
Columns           : 9
Missing Values    : 0
================================================================================

           Date  Year Quarter  Month Month_Name  Week  Day  Day_Name  Weekday
1622 2023-07-21  2023      Q3      7       July    29   21    Friday        5
875  2023-07-22  2023      Q3      7       July    29   22  Saturday        6
1962 2023-07-23  2023      Q3      7       July    29   23    Sunday        7
221  2023-07-24  2023      Q3      7       July    30   24    Monday        1
429  2023-07-25  2023      Q3      7       July    30   25   Tuesday        2

In [22]:
print("="*80)
print("DATE DIMENSION VALIDATION")
print("="*80)

duplicates = dim_date["Date"].duplicated().sum()

print(f"Duplicate Dates : {duplicates}")
print(f"Unique Dates    : {dim_date['Date'].nunique():,}")
print(f"Total Records   : {len(dim_date):,}")

if duplicates == 0:
    print("\nSTATUS : PASSED")
else:
    print("\nSTATUS : FAILED")

================================================================================
DATE DIMENSION VALIDATION
================================================================================
Duplicate Dates : 0
Unique Dates    : 2,030
Total Records   : 2,030

STATUS : PASSED

In [23]:
print("="*80)
print("DATE DIMENSION PROFILE")
print("="*80)

dim_date.info()

print()

display(

    dim_date.describe(include="all").T

)

================================================================================
DATE DIMENSION PROFILE
================================================================================
<class 'pandas.core.frame.DataFrame'>
Index: 2030 entries, 1622 to 3536
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Date        2030 non-null   datetime64[ns]
 1   Year        2030 non-null   int32
 2   Quarter     2030 non-null   object
 3   Month       2030 non-null   int32
 4   Month_Name  2030 non-null   object
 5   Week        2030 non-null   int64
 6   Day         2030 non-null   int32
 7   Day_Name    2030 non-null   object
 8   Weekday     2030 non-null   int32
dtypes: datetime64[ns](1), int32(4), int64(1), object(3)
memory usage: 126.9+ KB

,count,unique,top,freq,mean,min,25%,50%,75%,max,std
Date,2030,NaN,NaN,NaN,2026-05-06 22:36:17.733990144,2023-07-21 00:00:00,2024-12-09 06:00:00,2026-04-30 12:00:00,2027-09-26 18:00:00,2029-06-29 00:00:00,NaN
Year,"2,030.00",NaN,NaN,NaN,"2,025.84","2,023.00","2,024.00","2,026.00","2,027.00","2,029.00",1.67
Quarter,2030,4,Q4,531,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Month,"2,030.00",NaN,NaN,NaN,6.59,1.00,4.00,7.00,10.00,12.00,3.48
Month_Name,2030,12,October,184,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Week,"2,030.00",NaN,NaN,NaN,26.91,1.00,14.00,27.00,40.00,53.00,15.18
Day,"2,030.00",NaN,NaN,NaN,15.78,1.00,8.00,16.00,23.00,31.00,8.85
Day_Name,2030,7,Saturday,293,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Weekday,"2,030.00",NaN,NaN,NaN,4.01,1.00,2.00,4.00,6.00,7.00,2.00

In [24]:
dim_date.to_csv(

    dashboard_folder /

    "Dim_Date.csv",

    index=False

)

print("="*80)
print("Dim_Date EXPORTED SUCCESSFULLY")
print("="*80)

print(dashboard_folder / "Dim_Date.csv")

================================================================================
Dim_Date EXPORTED SUCCESSFULLY
================================================================================
..\..\outputs\dashboard_data\Dim_Date.csv

In [25]:
file_path = dashboard_folder / "Dim_Date.csv"

print("="*80)
print("EXPORT VALIDATION")
print("="*80)

if os.path.exists(file_path):

    print("STATUS : SUCCESS")

    print(f"File Name : {file_path.name}")

    print(f"File Size : {round(os.path.getsize(file_path)/1024,2)} KB")

else:

    print("STATUS : FAILED")

================================================================================
EXPORT VALIDATION
================================================================================
STATUS : SUCCESS
File Name : Dim_Date.csv
File Size : 89.57 KB

# SECTION E — Fact Table (Fact_Medicine_Performance)

## Objective

Create the central Fact Table for the Power BI Star Schema.

Each record represents the performance of one medicine inventory record and contains all measurable business metrics required for analytical reporting.

### Foreign Keys

- Medicine_ID
- Supplier_ID
- Category_ID

### Measures

- Revenue
- Inventory Value
- Profit
- Waste
- Inventory KPIs
- Sales KPIs
- Executive KPIs

This table serves as the primary source for all Power BI visualizations.

In [26]:
print("="*80)
print("CREATING FACT_MEDICINE_PERFORMANCE")
print("="*80)

fact_columns = [

    # Keys
    "Inventory_ID",
    "Medicine_ID",
    "Supplier_ID",
    "Category_ID",

    # Dates
    "Manufacturing_Date",
    "Expiry_Date",
    "Last_Restock_Date",

    # Inventory Measures
    "Quantity_In_Stock",
    "Unit_Cost",
    "Selling_Price",
    "Inventory_Value",
    "Potential_Sales_Value",
    "Potential_Gross_Profit",

    # Sales Measures
    "Total_Revenue",
    "Total_Quantity_Sold",
    "Revenue_per_Transaction",
    "Revenue_per_Unit_Sold",

    # Waste Measures
    "Total_Waste_Value",
    "Total_Quantity_Wasted",
    "Waste_Percentage",
    "Waste_Cost_Ratio",

    # Financial Measures
    "Profit_per_Unit",
    "Profit_Margin_Percentage",
    "Markup_Percentage",
    "Inventory_ROI",
    "Cost_to_Revenue_Ratio",

    # Inventory KPIs
    "Days_to_Expiry",
    "Inventory_Age_Days",
    "Days_Since_Last_Restock",
    "Stock_Difference",
    "Stock_Coverage_Ratio",

    # Business Flags
    "Low_Stock_Flag",
    "Overstock_Flag",
    "Out_of_Stock_Flag",
    "Near_Expiry_Flag",

    # Classifications
    "ABC_Class",
    "Movement_Type",
    "Waste_Risk",
    "Supplier_Risk",
    "Business_Priority",
    "Inventory_Criticality",
    "Stock_Priority",
    "Executive_Priority",

    # Scores
    "Inventory_Health_Score",
    "Sales_Performance_Score",
    "Supplier_Performance_Index",
    "Executive_Risk_Score"

]

fact_medicine_performance = feature_store[fact_columns].copy()

print(f"Rows              : {fact_medicine_performance.shape[0]:,}")
print(f"Columns           : {fact_medicine_performance.shape[1]}")
print(f"Duplicate Rows    : {fact_medicine_performance.duplicated().sum()}")
print(f"Missing Values    : {fact_medicine_performance.isnull().sum().sum()}")

print("="*80)

display(fact_medicine_performance.head())

================================================================================
CREATING FACT_MEDICINE_PERFORMANCE
================================================================================
Rows              : 4,954
Columns           : 47
Duplicate Rows    : 0
Missing Values    : 0
================================================================================

,Inventory_ID,Medicine_ID,Supplier_ID,Category_ID,Manufacturing_Date,Expiry_Date,Last_Restock_Date,Quantity_In_Stock,Unit_Cost,Selling_Price,Inventory_Value,Potential_Sales_Value,Potential_Gross_Profit,Total_Revenue,Total_Quantity_Sold,Revenue_per_Transaction,Revenue_per_Unit_Sold,Total_Waste_Value,Total_Quantity_Wasted,Waste_Percentage,Waste_Cost_Ratio,Profit_per_Unit,Profit_Margin_Percentage,Markup_Percentage,Inventory_ROI,Cost_to_Revenue_Ratio,Days_to_Expiry,Inventory_Age_Days,Days_Since_Last_Restock,Stock_Difference,Stock_Coverage_Ratio,Low_Stock_Flag,Overstock_Flag,Out_of_Stock_Flag,Near_Expiry_Flag,ABC_Class,Movement_Type,Waste_Risk,Supplier_Risk,Business_Priority,Inventory_Criticality,Stock_Priority,Executive_Priority,Inventory_Health_Score,Sales_Performance_Score,Supplier_Performance_Index,Executive_Risk_Score
0,INV002361,MED000911,SUP0048,CAT005,2026-03-06,2027-03-31,2026-05-07,993,596.32,798.36,"592,145.76","792,771.48","200,625.72",0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,202.04,25.31,33.88,33.88,74.69,236,154,92,906,11.41,0,1,0,0,A,Slow Moving,Low,Low,Low,High,Reduce Inventory,Medium,90,25.40,76.00,66.79
1,INV004233,MED056437,SUP0058,CAT015,2026-03-05,2027-03-30,2026-04-23,986,597.63,806.78,"589,263.18","795,485.08","206,221.90","1,593.69",6.00,531.23,265.62,"2,390.52",4.00,0.41,0.00,209.15,25.92,35.00,35.00,74.08,235,155,106,868,8.36,0,1,0,0,A,Medium Moving,Low,Low,Low,High,Reduce Inventory,Medium,90,59.56,82.00,79.59
2,INV003424,MED000320,SUP0031,CAT004,2026-01-22,2028-05-11,2026-03-21,965,596.60,723.41,"575,719.00","698,090.65","122,371.65",629.68,1.00,629.68,629.68,"4,772.80",8.00,0.83,0.01,126.81,17.53,21.26,21.26,82.47,643,197,139,773,5.03,0,1,0,0,A,Slow Moving,Low,Low,Low,High,Reduce Inventory,Medium,90,16.67,80.00,64.21
3,INV000760,MED096650,SUP0014,CAT015,2023-11-01,2025-12-20,2024-03-12,979,584.92,793.34,"572,636.68","776,679.86","204,043.18","2,997.35",6.00,"2,997.35",499.56,"10,528.56",18.00,1.84,0.02,208.42,26.27,35.63,35.63,73.73,-230,1010,878,926,18.47,0,1,0,1,A,Medium Moving,Low,Medium,Medium,Critical,Reduce Inventory,Medium,65,68.80,71.00,72.20
4,INV003192,MED117869,SUP0010,CAT015,2023-11-10,2025-08-31,2024-03-16,998,572.69,774.24,"571,544.62","772,691.52","201,146.90",332.00,1.00,332.00,332.00,0.00,0.00,0.00,0.00,201.55,26.03,35.19,35.19,73.97,-341,1001,874,966,31.19,0,1,0,1,A,Slow Moving,Low,Medium,Low,Critical,Reduce Inventory,Medium,75,35.54,88.00,66.89

In [27]:
print("="*80)
print("FACT TABLE VALIDATION")
print("="*80)

print(f"Inventory Records : {fact_medicine_performance['Inventory_ID'].nunique():,}")
print(f"Medicines         : {fact_medicine_performance['Medicine_ID'].nunique():,}")
print(f"Suppliers         : {fact_medicine_performance['Supplier_ID'].nunique():,}")
print(f"Categories        : {fact_medicine_performance['Category_ID'].nunique():,}")

print()

print("Primary Key Check")

duplicate_inventory = fact_medicine_performance["Inventory_ID"].duplicated().sum()

print(f"Duplicate Inventory_ID : {duplicate_inventory}")

if duplicate_inventory == 0:
    print("\nSTATUS : PASSED")
else:
    print("\nSTATUS : FAILED")

================================================================================
FACT TABLE VALIDATION
================================================================================
Inventory Records : 4,954
Medicines         : 4,824
Suppliers         : 75
Categories        : 14

Primary Key Check
Duplicate Inventory_ID : 0

STATUS : PASSED

In [28]:
print("="*80)
print("FACT TABLE PROFILE")
print("="*80)

fact_medicine_performance.info()

print()

display(

    fact_medicine_performance.describe(include="all").T

)

================================================================================
FACT TABLE PROFILE
================================================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4954 entries, 0 to 4953
Data columns (total 47 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Inventory_ID                4954 non-null   object
 1   Medicine_ID                 4954 non-null   object
 2   Supplier_ID                 4954 non-null   object
 3   Category_ID                 4954 non-null   object
 4   Manufacturing_Date          4954 non-null   object
 5   Expiry_Date                 4954 non-null   object
 6   Last_Restock_Date           4954 non-null   object
 7   Quantity_In_Stock           4954 non-null   int64
 8   Unit_Cost                   4954 non-null   float64
 9   Selling_Price               4954 non-null   float64
 10  Inventory_Value             4954 non-null   float64
 11  Potential_Sales_Value       4954 non-null   float64
 12  Potential_Gross_Profit      4954 non-null   float64
 13  Total_Revenue               4954 non-null   float64
 14  Total_Quantity_Sold         4954 non-null   float64
 15  Revenue_per_Transaction     4954 non-null   float64
 16  Revenue_per_Unit_Sold       4954 non-null   float64
 17  Total_Waste_Value           4954 non-null   float64
 18  Total_Quantity_Wasted       4954 non-null   float64
 19  Waste_Percentage            4954 non-null   float64
 20  Waste_Cost_Ratio            4954 non-null   float64
 21  Profit_per_Unit             4954 non-null   float64
 22  Profit_Margin_Percentage    4954 non-null   float64
 23  Markup_Percentage           4954 non-null   float64
 24  Inventory_ROI               4954 non-null   float64
 25  Cost_to_Revenue_Ratio       4954 non-null   float64
 26  Days_to_Expiry              4954 non-null   int64
 27  Inventory_Age_Days          4954 non-null   int64
 28  Days_Since_Last_Restock     4954 non-null   int64
 29  Stock_Difference            4954 non-null   int64
 30  Stock_Coverage_Ratio        4954 non-null   float64
 31  Low_Stock_Flag              4954 non-null   int64
 32  Overstock_Flag              4954 non-null   int64
 33  Out_of_Stock_Flag           4954 non-null   int64
 34  Near_Expiry_Flag            4954 non-null   int64
 35  ABC_Class                   4954 non-null   object
 36  Movement_Type               4954 non-null   object
 37  Waste_Risk                  4954 non-null   object
 38  Supplier_Risk               4954 non-null   object
 39  Business_Priority           4954 non-null   object
 40  Inventory_Criticality       4954 non-null   object
 41  Stock_Priority              4954 non-null   object
 42  Executive_Priority          4954 non-null   object
 43  Inventory_Health_Score      4954 non-null   int64
 44  Sales_Performance_Score     4954 non-null   float64
 45  Supplier_Performance_Index  4954 non-null   float64
 46  Executive_Risk_Score        4954 non-null   float64
dtypes: float64(22), int64(10), object(15)
memory usage: 1.8+ MB

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Inventory_ID,4954,4954,INV002163,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Medicine_ID,4954,4824,MED134145,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Supplier_ID,4954,75,SUP0040,87,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Category_ID,4954,14,CAT015,1788,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Manufacturing_Date,4954,1084,2025-02-09,13,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Expiry_Date,4954,1531,2026-11-10,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Last_Restock_Date,4954,1038,2026-07-20,467,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Quantity_In_Stock,"4,954.00",NaN,NaN,NaN,494.72,284.52,0.00,257.00,494.00,741.75,"1,000.00"
Unit_Cost,"4,954.00",NaN,NaN,NaN,299.44,172.54,5.12,152.29,295.09,448.43,599.99
Selling_Price,"4,954.00",NaN,NaN,NaN,389.01,225.00,6.18,196.32,380.89,580.52,835.39
Inventory_Value,"4,954.00",NaN,NaN,NaN,"147,991.08","129,049.92",0.00,"40,794.56","111,849.69","228,258.96","592,145.76"
Potential_Sales_Value,"4,954.00",NaN,NaN,NaN,"192,186.22","167,834.26",0.00,"53,081.07","145,264.48","296,697.85","795,485.08"
Potential_Gross_Profit,"4,954.00",NaN,NaN,NaN,"44,195.14","40,036.43",0.00,"11,808.67","32,387.25","67,559.66","221,129.92"
Total_Revenue,"4,954.00",NaN,NaN,NaN,"2,884.98","2,970.46",0.00,746.50,"1,984.62","4,202.11","19,932.10"
Total_Quantity_Sold,"4,954.00",NaN,NaN,NaN,5.02,4.48,0.00,2.00,4.00,7.00,27.00
Revenue_per_Transaction,"4,954.00",NaN,NaN,NaN,"1,221.87","1,114.20",0.00,485.52,984.22,"1,673.03","10,133.80"
Revenue_per_Unit_Sold,"4,954.00",NaN,NaN,NaN,503.92,310.59,0.00,281.60,522.41,738.49,"1,198.85"
Total_Waste_Value,"4,954.00",NaN,NaN,NaN,"14,665.15","24,086.51",0.00,0.00,510.35,"21,503.90","176,116.05"
Total_Quantity_Wasted,"4,954.00",NaN,NaN,NaN,48.57,65.08,0.00,0.00,3.00,93.75,374.00
Waste_Percentage,"4,954.00",NaN,NaN,NaN,15.77,31.33,0.00,0.00,1.27,20.81,634.82
Waste_Cost_Ratio,"4,954.00",NaN,NaN,NaN,0.16,0.31,0.00,0.00,0.01,0.21,6.35
Profit_per_Unit,"4,954.00",NaN,NaN,NaN,89.57,55.29,1.06,43.75,85.19,129.65,237.59
Profit_Margin_Percentage,"4,954.00",NaN,NaN,NaN,22.80,3.70,0.00,19.90,23.06,25.91,28.57
Markup_Percentage,"4,954.00",NaN,NaN,NaN,29.93,5.78,20.00,24.87,29.98,34.98,39.99
Inventory_ROI,"4,954.00",NaN,NaN,NaN,29.83,6.05,0.00,24.84,29.97,34.98,39.99
Cost_to_Revenue_Ratio,"4,954.00",NaN,NaN,NaN,76.83,5.77,0.00,74.06,76.90,80.07,83.33
Days_to_Expiry,"4,954.00",NaN,NaN,NaN,157.06,386.61,-748.00,-130.00,155.00,452.00,"1,057.00"
Inventory_Age_Days,"4,954.00",NaN,NaN,NaN,563.97,319.90,18.00,285.00,558.00,846.00,"1,113.00"
Days_Since_Last_Restock,"4,954.00",NaN,NaN,NaN,471.74,314.57,18.00,189.00,464.00,742.00,"1,094.00"
Stock_Difference,"4,954.00",NaN,NaN,NaN,382.01,288.28,-196.00,141.00,376.00,623.75,971.00
Stock_Coverage_Ratio,"4,954.00",NaN,NaN,NaN,5.80,5.39,0.00,2.23,4.36,7.38,37.65
Low_Stock_Flag,"4,954.00",NaN,NaN,NaN,0.11,0.32,0.00,0.00,0.00,0.00,1.00
Overstock_Flag,"4,954.00",NaN,NaN,NaN,0.66,0.47,0.00,0.00,1.00,1.00,1.00
Out_of_Stock_Flag,"4,954.00",NaN,NaN,NaN,0.00,0.06,0.00,0.00,0.00,0.00,1.00
Near_Expiry_Flag,"4,954.00",NaN,NaN,NaN,0.44,0.50,0.00,0.00,0.00,1.00,1.00
ABC_Class,4954,3,A,2201,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Movement_Type,4954,3,Slow Moving,1774,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Waste_Risk,4954,4,Low,2721,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Supplier_Risk,4954,3,Low,3192,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Business_Priority,4954,2,Low,3896,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Inventory_Criticality,4954,4,Low,1537,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Stock_Priority,4954,4,Reduce Inventory,3271,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Executive_Priority,4954,4,Medium,3350,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Inventory_Health_Score,"4,954.00",NaN,NaN,NaN,84.96,13.26,60.00,75.00,90.00,100.00,100.00
Sales_Performance_Score,"4,954.00",NaN,NaN,NaN,50.01,21.24,4.64,33.28,49.75,66.78,99.80
Supplier_Performance_Index,"4,954.00",NaN,NaN,NaN,78.39,7.32,63.00,72.00,78.00,85.00,92.00
Executive_Risk_Score,"4,954.00",NaN,NaN,NaN,71.63,10.09,-30.43,65.21,71.88,78.69,97.94

In [29]:
fact_medicine_performance.to_csv(

    dashboard_folder /

    "Fact_Medicine_Performance.csv",

    index=False

)

print("="*80)
print("FACT TABLE EXPORTED SUCCESSFULLY")
print("="*80)

print(dashboard_folder / "Fact_Medicine_Performance.csv")

PermissionError: [Errno 13] Permission denied: '..\\..\\outputs\\dashboard_data\\Fact_Medicine_Performance.csv'

In [30]:
file_path = dashboard_folder / "Fact_Medicine_Performance.csv"

print("="*80)
print("EXPORT VALIDATION")
print("="*80)

if os.path.exists(file_path):

    print("STATUS : SUCCESS")

    print(f"File Name : {file_path.name}")

    print(f"File Size : {round(os.path.getsize(file_path)/1024,2)} KB")

else:

    print("STATUS : FAILED")

================================================================================
EXPORT VALIDATION
================================================================================
STATUS : SUCCESS
File Name : Fact_Medicine_Performance.csv
File Size : 1850.63 KB

# SECTION F — Executive KPI Table

## Objective

Create a lightweight KPI table for Power BI card visuals.

This table contains high-level business metrics that will be displayed on the Executive Dashboard.

In [31]:
print("="*80)
print("CREATING EXECUTIVE KPI TABLE")
print("="*80)

executive_kpis = pd.DataFrame({

    "KPI":[

        "Total Revenue",
        "Inventory Value",
        "Potential Sales",
        "Potential Profit",
        "Total Waste",
        "Medicines",
        "Suppliers",
        "Categories",
        "Average Profit Margin",
        "Average Supplier Rating"

    ],

    "Value":[

        feature_store["Total_Revenue"].sum(),

        feature_store["Inventory_Value"].sum(),

        feature_store["Potential_Sales_Value"].sum(),

        feature_store["Potential_Gross_Profit"].sum(),

        feature_store["Total_Waste_Value"].sum(),

        feature_store["Medicine_ID"].nunique(),

        feature_store["Supplier_ID"].nunique(),

        feature_store["Category_ID"].nunique(),

        round(feature_store["Profit_Margin_Percentage"].mean(),2),

        round(feature_store["Supplier_Rating"].mean(),2)

    ]

})

display(executive_kpis)

================================================================================
CREATING EXECUTIVE KPI TABLE
================================================================================

                       KPI          Value
0            Total Revenue  14,292,183.85
1          Inventory Value 733,147,804.56
2          Potential Sales 952,090,541.76
3         Potential Profit 218,942,737.20
4              Total Waste  72,651,153.72
5                Medicines       4,824.00
6                Suppliers          75.00
7               Categories          14.00
8    Average Profit Margin          22.80
9  Average Supplier Rating           4.34

In [32]:
executive_kpis.to_csv(

    dashboard_folder /

    "Executive_KPIs.csv",

    index=False

)

print("="*80)
print("Executive_KPIs.csv EXPORTED")
print("="*80)

================================================================================
Executive_KPIs.csv EXPORTED
================================================================================

# SECTION G — Dashboard Filters

## Objective

Create reusable lookup tables for Power BI slicers.

These tables improve dashboard usability while avoiding duplicated values.

In [33]:
print("="*80)
print("CREATING DASHBOARD FILTERS")
print("="*80)

dashboard_filters = {

    "Category_Filter": sorted(feature_store["Category_Name"].dropna().unique()),

    "Supplier_Filter": sorted(feature_store["Supplier_Name"].dropna().unique()),

    "ABC_Filter": sorted(feature_store["ABC_Class"].dropna().unique()),

    "Priority_Filter": sorted(feature_store["Business_Priority"].dropna().unique()),

    "Waste_Filter": sorted(feature_store["Waste_Risk"].dropna().unique()),

    "Movement_Filter": sorted(feature_store["Movement_Type"].dropna().unique())

}

dashboard_filters

================================================================================
CREATING DASHBOARD FILTERS
================================================================================

{'Category_Filter': ['Allergy',
  'Antibiotics',
  'Cardiovascular',
  'Dermatology',
  'Diabetes',
  'Gastrointestinal',
  'Neurology',
  'Oncology',
  'Ophthalmology',
  'Others',
  'Pain Management',
  'Respiratory',
  'Vaccines & Biologics',
  'Vitamins & Supplements'],
 'Supplier_Filter': ['Abbott India Ltd',
  'Ajanta Pharma Ltd',
  'Alembic Pharmaceuticals Ltd',
  'Alkem Laboratories Ltd',
  'Apex Pharma Traders',
  'Apollo Pharmacy Distribution',
  'Aurobindo Pharma Ltd',
  'Bayer Pharmaceuticals Pvt Ltd',
  'Biocon Ltd',
  'Cadila Pharmaceuticals Ltd',
  'CarePlus Distributors',
  'CareWell Medical Agencies',
  'Central Healthcare Suppliers',
  'Cipla Ltd',
  'City Medical Distributors',
  "Divi's Laboratories Ltd",
  "Dr. Reddy's Laboratories Ltd",
  'Eastern Pharma Distribution',
  'Elite Medical Agencies',
  'Emcure Pharmaceuticals Ltd',
  'Eris Lifesciences Ltd',
  'GSK Pharmaceuticals Ltd',
  'Galaxy Medical Suppliers',
  'Glenmark Pharmaceuticals Ltd',
  'Global Pharma Agencies',
  'Granules India Ltd',
  'HealthCare Wholesale Solutions',
  'HealthFirst Distributors',
  'Hetero Labs Ltd',
  'Intas Pharmaceuticals Ltd',
  'Ipca Laboratories Ltd',
  'Jai Pharma Agencies',
  'LifeCare Pharma Distributors',
  'LifeLine Pharma Agencies',
  'Lupin Ltd',
  'Mankind Pharma Ltd',
  'MedCore Healthcare',
  'MedPlus Health Services',
  'MediLink Healthcare',
  'MediServe Pharma',
  'Metro Pharma Suppliers',
  'Micro Labs Ltd',
  'Natco Pharma Ltd',
  'National Drug Suppliers',
  'National Pharma Traders',
  'Netmeds Distribution',
  'North India Medical Suppliers',
  'Nova Medical Traders',
  'Om Medical Corporation',
  'Pfizer India Ltd',
  'PharmEasy Supply Chain',
  'Prime Healthcare Traders',
  'Prime Medical Distributors',
  'RK Pharma Agencies',
  'Reliance Retail Pharma',
  'SV Medical Traders',
  'Sai Pharma Agencies',
  'Sanofi India Ltd',
  'Shree Medical Agencies',
  'Sigma Healthcare Suppliers',
  'South India Pharma Distributors',
  'Sri Balaji Medical Suppliers',
  'Strides Pharma Science Ltd',
  'Sun Pharmaceutical Industries Ltd',
  'Supreme Pharma Traders',
  'Tata 1mg Distribution',
  'Torrent Pharmaceuticals Ltd',
  'Trust Medical Distributors',
  'United Medical Suppliers',
  'Unity Pharma Traders',
  'Universal Pharma Traders',
  'Wellness Forever Distribution',
  'Western Medical Distributors',
  'Wockhardt Ltd',
  'Zydus Lifesciences Ltd'],
 'ABC_Filter': ['A', 'B', 'C'],
 'Priority_Filter': ['Low', 'Medium'],
 'Waste_Filter': ['Critical', 'High', 'Low', 'Medium'],
 'Movement_Filter': ['Fast Moving', 'Medium Moving', 'Slow Moving']}

In [34]:
for filter_name, values in dashboard_filters.items():

    pd.DataFrame(

        values,

        columns=[filter_name]

    ).to_csv(

        dashboard_folder /

        f"{filter_name}.csv",

        index=False

    )

print("="*80)
print("ALL DASHBOARD FILTERS EXPORTED")
print("="*80)

================================================================================
ALL DASHBOARD FILTERS EXPORTED
================================================================================

# SECTION H — Final Validation

## Objective

Validate all generated Power BI datasets before moving to the AI Recommendation Engine.

In [35]:
print("="*80)
print("VALIDATING DASHBOARD DATASETS")
print("="*80)

expected_files = [

    "Dim_Medicine.csv",

    "Dim_Category.csv",

    "Dim_Supplier.csv",

    "Dim_Date.csv",

    "Fact_Medicine_Performance.csv",

    "Executive_KPIs.csv",

    "Category_Filter.csv",

    "Supplier_Filter.csv",

    "ABC_Filter.csv",

    "Priority_Filter.csv",

    "Waste_Filter.csv",

    "Movement_Filter.csv"

]

validation = []

for file in expected_files:

    path = dashboard_folder / file

    validation.append({

        "File": file,

        "Exists": path.exists()

    })

validation_df = pd.DataFrame(validation)

display(validation_df)

print()

print(f"Files Generated : {validation_df['Exists'].sum()} / {len(expected_files)}")

if validation_df["Exists"].all():

    print("\nSTATUS : NOTEBOOK 06 COMPLETED SUCCESSFULLY")

else:

    print("\nSTATUS : SOME FILES ARE MISSING")

================================================================================
VALIDATING DASHBOARD DATASETS
================================================================================

                             File  Exists
0                Dim_Medicine.csv    True
1                Dim_Category.csv    True
2                Dim_Supplier.csv    True
3                    Dim_Date.csv    True
4   Fact_Medicine_Performance.csv    True
5              Executive_KPIs.csv    True
6             Category_Filter.csv    True
7             Supplier_Filter.csv    True
8                  ABC_Filter.csv    True
9             Priority_Filter.csv    True
10               Waste_Filter.csv    True
11            Movement_Filter.csv    True

Files Generated : 12 / 12

STATUS : NOTEBOOK 06 COMPLETED SUCCESSFULLY

# Notebook 06 Completion Summary

## Completed Outputs

- Dim_Medicine
- Dim_Category
- Dim_Supplier
- Dim_Date
- Fact_Medicine_Performance
- Executive_KPIs
- Dashboard Filter Tables

## Business Outcome

A complete Power BI Star Schema has been created and exported successfully. These datasets are optimized for dashboard development and will also serve as the data source for the AI Recommendation Engine in Notebook 07.